title: Kukkotarha
description: -Suomalaisen alkoholilainsäädännön puolesta alkaen vuodesta 2015-
email: kukkotarha@gmail.com
disclaimer: Tällä sivustolla ei ole kytköksiä Laitilan Virvoitusjuomatehtaaseen. Kehityskoneistoa on kylläkin voideltu Kukko lager oluella. Nam!

# 1Liners:
1liner1: Kukko tykkää tulla juoduksi!

# Slides
slides:
- {name: Rooster, thumb: 'rooster_thumb.jpg', fullsize: 'rooster_full.jpg', filename: rooster}
- {name: Cock, thumb: 'cock_thumb.jpg', fullsize: 'cock_full.jpg', filename: cock}